import { FastifyInstance } from 'fastify'
import { prisma } from '../shared/prisma'
import { SystemConfigService } from '../shared/system-config.service'
import { finalizePosPayment } from './pos-payment.service'
import { distributeSubscriptionCommission } from '../commissions/subscription-commission.service'

export async function asaasWebhookRoutes(app: FastifyInstance) {
  app.post('/webhook/asaas', {
    schema: {
      body: {
        type: 'object',
        properties: {
          event: { type: 'string' },
          payment: {
            type: 'object',
            properties: {
              id: { type: 'string' },
              status: { type: 'string' },
              externalReference: { type: 'string' },
              value: { type: 'number' },
              // Asaas' own recurring-subscription id — present on a payment
              // generated by a subscription cycle, absent on a one-off charge.
              subscription: { type: 'string' },
            },
            required: ['id'],
          },
        },
        required: ['event', 'payment'],
      },
    },
  }, async (request, reply) => {
    // 1. Verify webhook token
    const configuredToken = SystemConfigService.get('ASAAS_WEBHOOK_TOKEN')

    if (configuredToken) {
      const authHeader = request.headers['authorization']
      const tokenQuery = (request.query as Record<string, string>)['token']
      const receivedToken = authHeader ?? tokenQuery

      if (receivedToken !== configuredToken) {
        app.log.warn({ receivedToken }, 'asaas.webhook: token mismatch — rejecting request')
        return reply.status(401).send({ error: 'Unauthorized' })
      }
    } else {
      app.log.warn('asaas.webhook: ASAAS_WEBHOOK_TOKEN not configured — skipping token verification')
    }

    const { event, payment } = request.body as {
      event: string
      payment: { id: string; status?: string; externalReference?: string; value?: number; subscription?: string }
    }

    app.log.info({ event, paymentId: payment.id }, 'asaas.webhook: received event')

    // 2. Handle event types
    if (event === 'PAYMENT_CONFIRMED' || event === 'PAYMENT_RECEIVED') {
      const posPayment = await prisma.posPayment.findFirst({ where: { asaasChargeId: payment.id } })
      if (posPayment) {
        if (posPayment.status === 'AWAITING_PAYMENT') {
          await prisma.posPayment.update({ where: { id: posPayment.id }, data: { status: 'PAID', settledAt: new Date() } })
          await finalizePosPayment(posPayment.id)
          app.log.info({ posPaymentId: posPayment.id, event }, 'asaas.webhook: POS payment confirmed')
        } else {
          app.log.info({ posPaymentId: posPayment.id, status: posPayment.status }, 'asaas.webhook: POS payment already settled, ignoring duplicate event')
        }
        return reply.send({ ok: true })
      }

      const order = await prisma.order.findFirst({
        where: { asaasChargeId: payment.id },
      })

      if (order) {
        const updates: Record<string, unknown> = { paymentStatus: 'PAID' }
        if (order.status === 'PENDING') {
          updates.status = 'CONFIRMED'
        }

        await prisma.order.update({
          where: { id: order.id },
          data: updates,
        })

        app.log.info({ orderId: order.id, event }, 'asaas.webhook: order payment confirmed')
        return reply.send({ ok: true })
      }

      // Recurring subscription charge (e.g. credenciador plan upgrade) — payment.id
      // is a one-off Asaas charge, payment.subscription is the recurring Asaas
      // subscription id it belongs to, which we stored as Subscription.asaasSubId
      // when the subscription was created. Activation and network commission
      // ONLY happen here, on confirmed payment — never at checkout time — so an
      // unpaid PIX never grants the plan or pays anyone.
      if (payment.subscription) {
        const subscription = await prisma.subscription.findFirst({ where: { asaasSubId: payment.subscription } })
        if (subscription) {
          const existingPayment = await prisma.subscriptionPayment.findUnique({ where: { asaasPaymentId: payment.id } })
          if (existingPayment) {
            app.log.info({ subscriptionId: subscription.id, event }, 'asaas.webhook: subscription payment already processed, ignoring duplicate event')
            return reply.send({ ok: true })
          }

          const plan = subscription.planId ? await prisma.plan.findUnique({ where: { id: subscription.planId } }) : null
          const cycleDays = plan?.billingCycle === 'YEARLY' ? 365 : 30
          const expiresAt = new Date(Date.now() + cycleDays * 24 * 60 * 60 * 1000)
          const amount = payment.value ?? (plan ? Number(plan.price) : 0)

          const subPayment = await prisma.$transaction(async (tx) => {
            const created = await tx.subscriptionPayment.create({
              data: { subscriptionId: subscription.id, userId: subscription.userId, amount, asaasPaymentId: payment.id },
            })
            await tx.subscription.update({ where: { id: subscription.id }, data: { isActive: true, expiresAt } })
            return created
          })

          await distributeSubscriptionCommission(subPayment.id)
          app.log.info({ subscriptionId: subscription.id, event }, 'asaas.webhook: subscription payment confirmed')
        }
        return reply.send({ ok: true })
      }

      app.log.warn({ paymentId: payment.id, event }, 'asaas.webhook: no order, POS payment or subscription found for paymentId')
      return reply.send({ ok: true, event: 'not_found' })
    }

    if (event === 'PAYMENT_OVERDUE' || event === 'PAYMENT_DELETED') {
      const posPayment = await prisma.posPayment.findFirst({ where: { asaasChargeId: payment.id } })
      if (posPayment) {
        if (posPayment.status === 'AWAITING_PAYMENT') {
          await prisma.posPayment.update({ where: { id: posPayment.id }, data: { status: 'CANCELLED' } })
          app.log.info({ posPaymentId: posPayment.id, event }, 'asaas.webhook: POS payment cancelled/overdue')
        }
        return reply.send({ ok: true })
      }

      const order = await prisma.order.findFirst({
        where: { asaasChargeId: payment.id },
      })

      if (!order) {
        app.log.warn({ paymentId: payment.id, event }, 'asaas.webhook: no order or POS payment found for paymentId')
        return reply.send({ ok: true, event: 'not_found' })
      }

      await prisma.order.update({
        where: { id: order.id },
        data: { paymentStatus: 'FAILED' },
      })

      app.log.info({ orderId: order.id, event }, 'asaas.webhook: order payment marked as failed')
      return reply.send({ ok: true })
    }

    // Any other event — ignore gracefully
    app.log.info({ event }, 'asaas.webhook: ignoring unhandled event')
    return reply.send({ ok: true, event: 'ignored' })
  })
}
