-- Portal login fields for DISTRIBUTOR / CREDENCIADOR / ESTABLISHMENT staff
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "passwordHash" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "distributorId" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "establishmentId" TEXT;
